### PR TITLE
Recording edls

### LINKED ISSUE #174: Timer Recording not displaying description - Not being stored on STB - AddTimer Call
From "garret: on Kodi Forum:

If I have understand this right, when Kodi is showing description to recording it parses this information from Enigma's *.meta file.

When I add recording to STB from Kodi's EPG, I cannot see description in Kodi because it doesn't exist in meta-file. Kodi will lost it somehow. In STB I can see description, because it uses information from *.eit -file.

If I add recording from OpenWebif, description is present. This have been tested with different Kodi OS, Enigma-images, Webif versions and skins with same result. Also with newest Milhouse build.

Here you can see difference between recordings which are made in STB and Kodi:

image

As soon I have placed new recording, description is lost. This can be verified from timers.xml in STB. It's only containing recording time.

Ps. I dont know does this help, but In Finland terrestial broadcasters usually doesn't use "extended event description" -information at all. Just "event description". Thats why "Plot" is usually empty and needed information can be found at "PlotOutline".

It doesn't matter how you make this timer. If its made from Kodi, description is lost. And in descrption field is recording time.

Example.

I made two timers, first from Webif, second from Kodi EPG. Same program.

image

image

### LINKED ISSUE #178: Some users only have a Last Scanned bouquet - Need to support it
As last scanned contains both TV and Radio Channels it was not used as a bouquet/group. Will need to identify as a radio service type to allow it's use for TV and radio

### PR DESCRIPTION
**Pull request by phunkyfish**
v3.17.0
- Added: Recording EDL support
- Added: Update Timer Types to display correctly in Manual vs EPG UIs
- Added: Updated show info regex's
- Fixed: Timer Recording not displaying description - Not being stored on STB - AddTimer Call, fixes #174
- Fixed: Fix for uncaught type_error for nlohmann/json
- Fixed: Include TV Favourites channels by default in settings
- Added: Support Last Scanned for both TV and Radio, fixes #178
- Fixed: Null pointer check for Genre EPG data processed XML

### CODE REVIEW

**Comment by phunkyfish** [comment]
@ksooo the horrible Macro is finally gone!

**Comment by phunkyfish** [comment]
@alanwww1 @ksooo 

Is there anyway I can run the transifex update so I can incorporate into my PR?

**Comment by phunkyfish** [comment]
@ksooo I assume you are up the walls with the kodi 18 release but if you have some time to review that  would be awesome!

**Comment by phunkyfish** [comment]
I have a few minor addition I'll add later today. Will let you know once they are in.

**Comment by phunkyfish** [comment]
Ok, all there now. Added bonus, fix confirmed fixed by users. Thanks again @MilhouseSV for including in testbuilds.

**Comment by phunkyfish** [comment]
There is an uncaught exception for nlohmann json that i need to add a fix for.

**Comment by phunkyfish** [comment]
Ok, should be ready

**Comment by phunkyfish** [comment]
I have yet another fix. So many enigma images and so many peculiarities. Will post back once ready.

**Comment by phunkyfish** [comment]
Ok, that should cover all the issues raised since the Kodi 18 release that I'm aware of.

**Comment by phunkyfish** [comment]
@ksooo would be great to get this reviewed. There are a number of users who have no PVR functionality to differences in Engima2 images and hardware that I wasn't aware of. The fixes included with this PR should them up and running.

Thanks in advance.

**Comment by phunkyfish** [comment]
Hey @Rechi 

I'm getting a strange build error:

```
Creating placeholder flownodes because failed loading originals.

GitHub has been notified of this commit’s build result

java.io.IOException: Tried to load head FlowNodes for execution Owner[kodi-pvr/pvr.vuplus/PR-177/9:kodi-pvr/pvr.vuplus/PR-177 #9] but FlowNode was not found in storage for head id:FlowNodeId 1:36
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.initializeStorage(CpsFlowExecution.java:678)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:715)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:664)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:526)
	at hudson.model.RunMap.retrieve(RunMap.java:225)
	at hudson.model.RunMap.retrieve(RunMap.java:57)
```

Prior to this I mistakenly pushed a branch which I then removed. Not sure if that's related.

**Comment by phunkyfish** [comment]
Nevermind, it appears it self resolved.

**Comment by phunkyfish** [comment]
Will do 😉

**Comment by phunkyfish** [comment]
Ah, I see what happened. Latest version of VSCode has remove whitespace on save enabled.

**Comment by phunkyfish** [comment]
Will give source a once through before next PR.

**Comment by ksooo** [comment]
> Will give source a once through before next PR.

👍

**Pull request merged**
