### PR TITLE
Fix spelling errors

### LINKED ISSUE #291: Fix spelling errors reported by Lintian
`configuraton`:
https://github.com/kodi-pvr/pvr.vuplus/blob/9f71c7297d947833c69a5470a9b841c1b31bc2d9/src/Enigma2.cpp#L151
`Transfered`:
https://github.com/kodi-pvr/pvr.vuplus/blob/9f71c7297d947833c69a5470a9b841c1b31bc2d9/src/Enigma2.cpp#L844

@phunkyfish

### PR DESCRIPTION
**Pull request by basilgello**
Closes #291

### CODE REVIEW

**Comment by phunkyfish** [comment]
Do you want this released?

If so you need to update the addon xml and changelog.

**Comment by basilgello** [comment]
> Do you want this released?
> 
> If so you need to update the addon xml and changelog.

Yes, I do. I will update them now!

**Comment by phunkyfish** [comment]
There is also a changelog in addon xml for vuplus. Once you add it there too this is good.

**Comment by basilgello** [comment]
> There is also a changelog in addon xml for vuplus. Once you add it there too this is good.

Done!

**Review by phunkyfish — APPROVED** [review]
👍

**Pull request merged**
