### PR TITLE
update README.md to show appveyor

### PR DESCRIPTION
**Pull request by AlwinEsch**
The addon is now also added to appveyor to see result,

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]

**Comment by AlwinEsch** [comment]
Not so fast, I'm currently not complete sure if the appveyor Link is really correct. :grinning:

**Comment by phunkyfish** [comment]
Whoops

**Comment by phunkyfish** [comment]
Something like this for Leia I think. Org should be kodi-pvr:

I think this: https://ci.appveyor.com/api/projects/status/github/kodi-pvr/pvr.vuplus?branch=Leia&svg=true

**Comment by phunkyfish** [comment]
I think you need to remove it from xbmc org as it’s already in kodi-pvr

**Comment by phunkyfish** [comment]
But it works either way 😉

**Pull request merged**
