### PR TITLE
Updated addon.xml.in to descriptions to reflect new cosmetic name

### PR DESCRIPTION
**Pull request by Hedda**
Updated addon.xml.in to descriptions to reflect the new cosmetic name of "Enigma2" and the fact that it is compatible with many different boxes from multiple manufacturers, (not just VU+ boxes).

### CODE REVIEW

**Comment by ksooo** [comment]
-1, sorry. This wont work.

Translations are handled via Transifex. Next automatic resync with Transifex would overwrite this changes.

**Comment by ksooo** [comment]
Sorry, this is the wrong way.

**Comment by Hedda** [comment]
@ksooo / @phunkyfish is even the English (GB or US original language?) only handled via Transifex?

What if I want to suggest a change for updated summary and description in the original English language to reflect the addon name change?

New 'en_GB'/'en_US' summary: "Kodi's PVR frontend client for Enigma2-based set-top boxes"

New 'en_GB'/'en_US' description: "Enigma2 PVR client addon; frontend supporting streaming of Live TV &amp; Recordings, EPG, Timers, Autotimers. Compatible with Enigma2-based TV-boxes from different manufacturers, such as Amiko, DBox2, Dreambox, Gigablue, SAB, VuPlus/Vu+, WeTek, Zgemma, Xtrend, and more."

Does that too have to go through Transifex?

**Comment by phunkyfish** [comment]
Only en_gb should be updated. Was there an issue with en_gb?

Transifex updates all other lanagues.

**Comment by phunkyfish** [comment]
Feel free to create an issue for the change you are proposing and we can discuss there.

**Comment by Hedda** [comment]
Submitted pull request #107 as a suggestion for a change of both summary and description in en_GB.

Please note that it is only a suggestion so feel free to reject, edit and merge, or accept that PR as it is.

**Pull request closed without merging**
