### PR TITLE
Sync with API 1.9.6

### PR DESCRIPTION
**Pull request by hudokkow**
Runtime tested in Ubuntu

### CODE REVIEW

**Comment by hudokkow** [comment]
@FernetMenta, can you add me to the organization so I can start taking care of these?

**Comment by Jalle19** [comment]
jenkins build addons please

**Comment by Jalle19** [comment]
Sorry for the spam, thought this was the Kodi repository...

**Comment by hudokkow** [comment]
If nobody objects I'll merge this tomorrow.

**Pull request merged**
