### PR TITLE
Fix recording margins

### PR DESCRIPTION
**Pull request by frankveltmans**
Corrected timer start and end time to include pre- and post-margin

### CODE REVIEW

**Comment by Jalle19** [comment]
ping @hudokkow

**Comment by Jalle19** [comment]
Closing this due to inactivity, please reopen if the PR should still be considered.

**Comment by slo617** [comment]
I would love to have this considered.
This would solve issue #47.
@Jalle19 It seems I do not have permission to reopen, I am not sure if @frankveltmans has. Can You reopen?
@Jalle19 What is missing to get this merged?
@frankveltmans Are you still there?

**Comment by Jalle19** [comment]
@slo617 nothing really except someone has to test it to make sure it actually works

**Comment by frankveltmans** [comment]
It works, i use it in all my kodi systems :)

**Comment by Jalle19** [comment]
Good to hear. @frankveltmans  Can you bump the addon version and add a changelog entry, then it's good to go?

**Comment by Jalle19** [comment]
@frankveltmans ping

**Pull request closed without merging**
