### PR TITLE
request live-stream-URL from OpenWebif instead of generating it

### PR DESCRIPTION
**Pull request by slo617**
Hello,

this fixes the alternative channels problem that is described in issue #20.
This is the same as pull request #21, but for the master branch.

Best regards,
Steffen.

### CODE REVIEW

**Comment by Jalle19** [comment]
ping @hudokkow

**Comment by varguello** [comment]
Any chance getting this change submitted in the near future?

**Comment by slo617** [comment]
Any comments are welcome.
I am using this for more than a year and it works good for me, but I might be a little bit biased.

I think about making this optional to make this change more backward compatible.
I also think about adding generic support for transcoding, which should also solve issue #25.

**Comment by varguello** [comment]
Any way to get an installable file with this change to install on a fire tv?

**Comment by slo617** [comment]
@varguello Sorry, I do not have Android builds. But the source code is available, so you can build it on your own.
Your might want to start here: https://github.com/kodi-pvr/pvr.vuplus -> readme.md
and here: http://kodi.wiki/view/Android_development

**Comment by slo617** [comment]
Is there a chance to get this merged? Is there anything I can do?

**Comment by Jalle19** [comment]
Can you bump the addon version and updatw the changelog? After that it's probably good to go.

**Comment by slo617** [comment]
I set the version to 3.3.1 and tested against dde9b24 once again.

**Comment by slo617** [comment]
It seems that Travis CI build has failed because one of the kodi mirrors was not reachable. Is there a way to trigger the test manually without pushing a new commit or will it retry automatically?

**Comment by Jalle19** [comment]
Not really. The addon may be broken at the moment anyway since the API has changed recently.

**Comment by Jalle19** [comment]
"Pull requests that have a failing status can’t be merged on a phone"

Ping me in a few days in case I forget

**Pull request merged**
