### PR TITLE
Streams for recordings

### PR DESCRIPTION
**Pull request by phunkyfish**
- Added: Recorded Streams support
- Added: PVR API 5.0.0: iChannelUid in recordings
- Added: PVR API 5.1.0: Support channel type in recordings

Also refactored some sources to group like functions together.

### CODE REVIEW

**Comment by phunkyfish** [comment]
Thanks, potentially ;)

It's been a number of years since I've been actively coding but I'm enjoying it. Can I ask what being a maintainer entails?

**Comment by ksooo** [comment]
If you're willing to take care of the addon 

* to look at the issues reported for the addon on github
* to respond to those issues
* to fix major issues
* to take action if mandatory addon API changes are to be done
* to implement new/missing features (if you are in the mood)

you are a good maintainer. Timewise nobody expects anything from you. You do only what your free time permits you to do.

**Comment by phunkyfish** [comment]
Sounds ok. Sign me up ;)

Also a question on settings.xml. I assume that if I move items between the
tabs I should not change the label IDs as this would mess with the
translations. Currently each tab has a range of label ids used, is it
important those ranges are respected or not?

**Comment by ksooo** [comment]
The ranges are not important for translation. But you should not change the id for an existing string. that breaks translation.

**Comment by ksooo** [comment]
> Sounds ok. Sign me up ;)

 Cool, thanks. There is no formal sign up process. Would be nice if you could have an eye on this repo and take action if you think it's the right time to do so.

 Also, it would be cool if you could keep an eye on the vuplus dev/support section in our forum. But that's just the icing on the cake.

**Comment by phunkyfish** [comment]
Just as I thought, thanks

**Comment by phunkyfish** [comment]
I can do that. Sounds good.

Another side question. For start and end padding is there is way to set the
default in kodi when adding a timer? I can set it once the timer exists
programatically but can't see how to do it when adding a new one on the UI.

**Comment by ksooo** [comment]
> For start and end padding is there is way to set the default in kodi when adding a timer? I can set it once the timer exists programatically but can't see how to do it when adding a new one on the UI.

 Currently, the addon can only provide default values for recording lifetime, timer priority and duplicate detection method.

 But there are global kodi settings for this. Values are taken for all addons: 
https://github.com/xbmc/xbmc/blob/master/system/settings/settings.xml#L1489 ff

**Comment by phunkyfish** [comment]
What I wanted to do is just have the margins defaults set when adding a
timer only. So they would need to be different between add and edit.
Enigma2 doesn't store the margins separately so setting it for all cases
would result in cumulative margins each time you edit as it can only set
the start and end time (which are modified before sending to Enigma2
device).

**Comment by phunkyfish** [comment]
I hadn’t tested it yet. Amazing that it already works that way!

Next question. Is it possible to set/access those settings from the addon dialog?

More of a curiosity than anything, totally fine with using the Kodi pvr settings for it.

**Comment by ksooo** [comment]
> Next question. Is it possible to set/access those settings from the addon dialog?

 Nope, and write access will never happen. An add-on must not override a Kodi global setting. Guess what happens if you have two pvr add-ons installed, both "fighting" to set their default value for the paging values.

 Right way is to do this via add-on specific settings like already done for instance for recording priority by pvr.hts

 This requires implementation in the core and an add-on API change. Doable, but not yet done. I will put this on my to-do list for v19.

**Comment by phunkyfish** [comment]
No worries, and thank you for answering another of my many questions ;)

**Pull request merged**
