### PR TITLE
Crash on addon start, fixes #191

### LINKED ISSUE #191: latest build crashes kodi
cant start kodi with enabled plugin anymore. just updated to the latest build. pvr.vuplus-3.18.0
stacktrace
https://paste.kodi.tv/zeqobibofa.kodi

and the last entrys of kodi before crash
https://paste.kodi.tv/tapupezafe.kodi

### PR DESCRIPTION
**Pull request by phunkyfish**
v3.18.1
- Fixed: Crash on addon start, fixes #191

### CODE REVIEW

**Comment by phunkyfish** [comment]
@ksooo Arrrgghhhh

I tested the wrong build after fixing the nitpicking which has broken the addon for a lot of users as just creating the shared_ptr has a null object. This will get them up and running.

A quick review would be appreciated!!!

**Comment by phunkyfish** [comment]
In future if something like this happens am I ok to merge without an approved review if the fix is obvious like this or should I always wait?

**Comment by ksooo** [comment]
> In future if something like this happens am I ok to merge without an approved review if the fix is obvious like this or should I always wait?

 Sure. You have proven several times that you have a clue. :-)

**Comment by ksooo** [comment]
OMG! It was me telling you bullshit about std::make_shared, right? Sorry for that.

**Comment by phunkyfish** [comment]
Ah sure if I had managed to test it properly instead of mucking it up this could have been avoided. You just gave me advice - which is almost always correct ;)

**Pull request merged**
