### PR TITLE
Add PVR Addon API 5.4.0 support

### PR DESCRIPTION
**Pull request by kenodai**
Topic should say it all.

### CODE REVIEW

**Comment by ksooo** [comment]
Thank. Have you runtime-tested the change against very latest kodi master and can you confirm that playing channels still works? For this, a working implementation of GetLiveStreamURL is essential. Formerly, this function was unused, but this has now changed. I've seen that the implementation of GetLiveStreamURL calls a function named SwitchChannel, which seems suspicious to me. Please check this.

Please note that you actually need a very recent kodi master. I merged an important fix today.

**Comment by kenodai** [comment]
To be honest.. no idea who implemented the GetLiveStreamURL and why it was implemented in the way it is.

Tested against d0e3f716 and was working.

**Comment by ksooo** [comment]
Perfect. Could you do me a favor and retest against at least 66fb905b?

**Comment by kenodai** [comment]
Tested against 898e273 still working.

**Comment by ksooo** [comment]
Cool. Thanks for retesting. Merging...

**Pull request merged**
