### PR TITLE
Added Support for Timer Types, complete with 3 types

### PR DESCRIPTION
**Pull request by phunkyfish**
Added: Timer Types Support, now supports Manual Once, Manual Repeating, EPG Once and EPG Repeating

### CODE REVIEW

**Comment by phunkyfish** [comment]
On Vu+ both once off and repeating timers are essentially a single static timer.

In the kodi UI these appear as Timers (once offs) and Timer Rules (repeating). Is this correct? I ask a because its a single timer for repeating when you click on time rule for it it takes you to an empty list of timers. But there will never be any child timers. Should this kind of repeating timer not appear in the Timers list instead?

**Comment by ksooo** [comment]
The timer / timer rules concept in a nutshell:

Timer
===
+ data set describing a single show to be recorded
+ appears in the "Timers" window in Kodi UI

timer rule
======
+ data set describing the conditions to be met to record certain shows
+ has the shows matching the rule criteria as children => a set of timers
+ appears in the "Timer rules" window in Kodi UI
+ clicking a timer rules entry in Kodi UI displays its children (the one off timers currently matching the rule)
+ "the timer rule is a factory for its child timers"
+ the addon must create and report the child timers itself to Kodi (in GetTimers implementation)

**Comment by phunkyfish** [comment]
Ok, understood. But in the case of Enigma2 a repeating timer is atomic. When I add support for autotimers the above will hold true. Would it be possible to make a change to have timer rules of both types. I.e. Timers like enigma2’s standard timers (no children) and autotimers (have children).

**Comment by ksooo** [comment]
We should try to adapt the enigma specific stuff to Kodi generic timer concept, that's what the add-on is for, not the other way around.

**Comment by phunkyfish** [comment]
Makes perfect sense. I'll have a think about how to implement this in the addon. Are you ok with merging the PR as is or would you prefer I add this support first? I guess I could limit the read only timers to only those in the next week.

As it stands it would be missing the child read only timers but is still perfectly functional.

**Comment by ksooo** [comment]
Obe thing that puzzles me is: A repeating timer schedules recordings right? Thus it is a timer rule in kodi speak. If so, why can't the addon evaluate that rule and create child timer instances for the shows matching the rule? The benefit for the user will be that he/she sees for instance which particular shows are actually scheduled for recording (the child timers), see a little clock icon attached to the respective epg events in epg window, etc pp.

**Comment by phunkyfish** [comment]
That is exactly what I am proposing to do. Exactly as you have stated. The kodi representation of those  would be read only as they would not exist on the Enigma2 STB. There are essentially 3 types of timers on the Enigma2.

1) One off timer. Just a single recording would result
2) A repeating timer. Would record on certain days/times. Many recordings would come from this but only a single timer exists for it.
3) An auto timer. The auto timer generates timers for any matching shows. 

It's case 2 where I would generate the read only timers. I havn't implemented case 3 yet as the autotimer API is not documented so I have to figure out how it works before going ahead with the implementation.

**Comment by phunkyfish** [comment]
There will be quite a bit of work to do case 2 as I'll have to query the EPG if it was used to create the timer rule to work out which EPG Ids to use for each timer. If it's ok with you can we merge the current PR and I'll work on case 2 as a separate PR over the next few weeks.

**Comment by phunkyfish** [comment]
Actually, I’m thinking about it a bit more one of my types should not be there. There is no point in having a repeating epg timer. This should only exist when the addon supports autotimers.

Let me make a change and I’ll update the PR. The only types should be manual once, manual repeating and EPG once.

**Comment by phunkyfish** [comment]
Ok, I've removed the 4th type which doesn't make any sense.

**Comment by phunkyfish** [comment]
If you'd like me to remove the manual repeating type too until I have the read only child timers done let me know. It doesn't cause any harm as it is.

**Comment by phunkyfish** [comment]
I had a look at the DVBViewer manual repeating timer and it's the same as the one in the PR. So it should be fine as it is.

**Pull request merged**
