### PR TITLE
Unique channels and radio groups

### LINKED ISSUE #101: Create unique list of channels instead of a copy of each channel per group
Currently the addon will create a channel for each occurrence of a channel in each group.

This is inefficient and there should be a single unique list of channels with groups referencing this list.

This should at least halve EPG load time for users who and an all channels group and use multiple groups.

### LINKED ISSUE #122: hdd free space is wrong
for me it show 3.10TB available of 3.70TB, but should be GB not TB

### PR DESCRIPTION
**Pull request by phunkyfish**
v3.15.0
- Added: Support for Radio Groups
- Added: Create unique list of channels instead of a copy of each channel per group, fixes #101, a nice performance boost for users
- Fixed: hdd free space is wrong, fixes #122

### CODE REVIEW

**Comment by phunkyfish** [comment]
@Rechi I don't appear to be able to access the jenkins details. It times out with 504, just wondering if there is an issue with it.

**Comment by Rechi** [comment]
@phunkyfish jenkins is responding again

**Comment by phunkyfish** [comment]
Thanks @Rechi

**Comment by phunkyfish** [comment]
@ksooo apologies, I didn’t realise this required a rebase

**Comment by phunkyfish** [comment]
If there are no objections I'm going to close this PR and reopen over the weekend as I have a few more fixes to add. It's getting to busy season at work and I won't have much spare time so would be good to get this all ready soon.

**Pull request closed without merging**
