### PR TITLE
Use recording filename

### PR DESCRIPTION
**Pull request by phunkyfish**
v6.2.0
- Added: If no recording metadata use filename for recording date if possible
- Update: Use add-on supplied StringUtils and remove local version

### CODE REVIEW

**Comment by phunkyfish** [comment]
@emveepee your suggestion implemented. Does it look ok to you?

**Comment by emveepee** [comment]
> 
> 
> @emveepee your suggestion implemented. Does it look ok to you?

It looks fine but not what I'd do  I'd start with a stronger regex  ([12]\d{3}[01]\d[0123]\d [01]\d{3}) and because this is only a display tag string I probably would build the year directly from regex groups.  (:?([12]\d{3})([01]\d)([0123]\d) [01]\d{3}) and live with the unlikely display risks.  

FWIW I found mktime() will return -1 on Windows in our last testing not really an issue here with recording times.

**Comment by phunkyfish** [comment]
Why would mktime() return -1?

**Comment by emveepee** [comment]
> 
> 
> Why would mktime() return -1?

If the tm time is before epoch time.  As I said this was just an FWIW

**Comment by phunkyfish** [comment]
Ah, yes, I remember now.

**Pull request merged**
