### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bservet**
And now for the Leia branch.

### CODE REVIEW

**Comment by phunkyfish** [comment]
This one is good. Thanks!

**Comment by bservet** [comment]
I couldn't further look into the squash and commit when I closed 223, but now there's only 224 left. So I hope that it's good to go :)

**Comment by phunkyfish** [comment]
As this text will also need to change for help info also I'll add this to the next PR. Cool?

**Comment by bservet** [comment]
Nice! :-)

**Pull request closed without merging**
